### ISSUE TITLE
你好，这个镜像很有用，感谢！但是好像jupyter lab没有启动

### ISSUE THREAD

**Issue by aipie0066** [leoatchina/dockerfile_jupyter#2]
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:bcPRVUAgJwLoK2QIA0oi0gC+veuah+bGXIrmtH4iBvQ root@9dd5a5c2247a (RSA)
Creating SSH2 DSA key; this may take some time ...
1024 SHA256:azpuSP5XJDxEwvTsijeMo/3VZvPjZPSryUHQ4/GWuC0 root@9dd5a5c2247a (DSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:6LCbDauThAk5AP5XL+7TMz4NWBsyGz0MfSGBtTXWFZ4 root@9dd5a5c2247a (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:fKy6FkVcfynyNjVOHjCr9pUw8NCNS+9XeWK0VfZbhVc root@9dd5a5c2247a (ED25519)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.

========================= starting services with USER datasci whose UID is 23333 ================================
rstudio-server.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable rstudio-server
 * Restarting RStudio Server rserver
   ...done.
2019-10-12 23:03:55,117 CRIT Supervisor running as root (no user in config file)
2019-10-12 23:03:55,119 INFO supervisord started with pid 145
2019-10-12 23:03:56,123 INFO spawned: 'code-server' with pid 184
2019-10-12 23:03:56,125 INFO spawned: 'sshd' with pid 185
2019-10-12 23:03:57,804 INFO success: code-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-12 23:03:57,804 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by leoatchina** [comment]
jupyterlab更新到1.1.4后因为权限问题，我把jupyterlab的启动改成手动了，周末更新

**Comment by leoatchina** [comment]
[最新一版](https://github.com/leoatchina/leoatchina-datasci/commit/44c39329f97d02be460d7bd460ed71e8c94f432d) 说明如何去手动启动，你看下。
