### ISSUE TITLE
entrypoint.sh修改小建议

### ISSUE THREAD

**Issue by wangshun1121** [leoatchina/dockerfile_jupyter#4]
https://github.com/leoatchina/leoatchina-datasci/blob/d371dbdb191dcce8f12fe78e9e72a61a5fe89626/entrypoint.sh#L36-L37
建议使用xargs调用多线程，来取代for循环赋权，实现加速。

示例代码见：

https://github.com/wangshun1121/bio_docker_collcetion/blob/master/PRJs/scrna_quant_analysis/entrypoint.sh

**Comment by leoatchina** [comment]
Good suggestions ! 我去试试

**Comment by leoatchina** [comment]
采用了你的建议，并且根据你的entrypoint把supervisor的配置改了， 同时能启动sshd和codeserver.
jupyterlab不建议自动启动，因为可能会激活不同的conda环境起相应的jupyerlab。
参见  https://github.com/leoatchina/leoatchina-datasci/commit/17e6dc831aaef0fc2293d545cbbb58d79648a350
